spring.application.name=enigmaOne

application.port=8080

spring.jackson.time-zone=America/Lima
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima

spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=jdbc:postgresql://localhost:5432/enigmaOne
#spring.datasource.username=arlinton
#Evitar caracteres como la "?" genera error
#spring.datasource.password=ConTRasDeACCes0


server.servlet.context-path=/api/enigmaOne

#JPA configuraciones
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update


Subida de imagenes
spring.datasource.url=jdbc:postgresql://${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Configuración para permitir subir archivos más grandes (p. ej. PDFs de varios MB)
# Ajusta según necesidad: 10MB por defecto
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Tamaño máximo internal validator (bytes) usado por FileSizeValidator. Por defecto 10MB
app.photo.max-size-bytes=10485760

# Cambiar puerto para evitar conflicto local
server.port=8081
