spring.application.name=enigmaOne

spring.jackson.time-zone=America/Lima
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jpa.properties.hibernate.jdbc.time_zone=America/Lima

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/enigmaOne
spring.datasource.username=arlinton

server.servlet.context-path=/api/enigmaOne

#Evitar caracteres como la "ñ" genera error
spring.datasource.password=ConTRasDeACCes0
#JPA configuraciones
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update


#Subida de imagenes

